<a href="https://colab.research.google.com/github/br0kic/Pemrograman_Python/blob/main/pertemuan%2011.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [6]:
cd /content/drive/MyDrive

/content/drive/MyDrive


In [7]:
ls

'1 Computer Architecture, Microprocessor and Microcontroller.pptx'
 3scene@
 best_weight_scene_mobileNet.h5
 Classroom/
 coast_art294.jpg
'Getting started.pdf'
 GMB_11@
 Maraden_quizz.pdf
 nnmodel_scene/
 nomer1.pdf
 nomer2.pdf
 nomer3.pdf
 quiz_jarkomdat_maraden.pdf
'Untitled folder'/


In [18]:
# import the necessary packages
from keras.models import Sequential
from keras.layers.core import Activation
from keras.layers.core import Flatten
from keras.layers.core import Dense
from keras.optimizers import Adam
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from PIL import Image
from imutils import paths
import numpy as np
import os

In [35]:
# grab all image paths in the input dataset directory, then initialize
# our list of images and corresponding class labels
print("[INFO] loading images...")
imagePaths = paths.list_images("GMB_11")
data = []
labels = []

[INFO] loading images...


In [36]:
# loop over our input images
for imagePath in imagePaths:
	# load the input image from disk, resize it to 64x64 pixels, scale
	# the pixel intensities to the range [0, 1], and then update our
	# images list
	image = Image.open(imagePath)
  #preprocessing
	image = np.array(image.resize((64, 64))) / 255.0 #normalisasi
	data.append(image)

	# extract the class label from the file path and update the
	# labels list
	label = imagePath.split(os.path.sep)[-1]
	labels.append(label)

In [37]:
print(labels)

['IMG_20200814_113250_HDR.jpg', 'IMG_20200814_113326_HDR.jpg', 'IMG_20200814_113333_HDR.jpg', 'IMG_20200814_113358_HDR.jpg', 'IMG_20200814_113422_HDR.jpg', 'IMG_20200814_113510_HDR.jpg', 'IMG_20200814_113831_HDR.jpg', 'IMG_20200814_113859_HDR.jpg', 'IMG_20200814_113905_HDR.jpg', 'IMG_20200814_113934_HDR.jpg', 'IMG_20200814_113939_HDR.jpg', 'IMG_20200814_113959_HDR.jpg', 'IMG_20200814_114036_HDR.jpg', 'IMG_20200814_114114_HDR.jpg', 'IMG_20200814_114154_HDR.jpg', 'IMG_20200814_114234_HDR.jpg', 'IMG_20200814_114307_HDR.jpg', 'IMG_20200814_114342_HDR.jpg', 'IMG_20200814_114417_HDR.jpg', 'IMG_20200814_114422_HDR.jpg', 'IMG_20200814_114602_HDR.jpg', 'IMG_20200814_114606_HDR.jpg', 'IMG_20200814_114633_HDR.jpg', 'IMG_20200814_114638_HDR.jpg', 'IMG_20200814_114712_HDR.jpg', 'IMG_20200814_114719_HDR.jpg', 'IMG_20200814_114801_HDR.jpg', 'IMG_20200814_114806_HDR.jpg', 'IMG_20200814_115004_HDR.jpg', 'IMG_20200814_115044_HDR.jpg', 'IMG_20200814_115050_HDR.jpg', 'IMG_20200814_115115_HDR.jpg', 'IMG_20

In [38]:
# encode the labels, converting them from strings to integers
lb = LabelBinarizer()
labels = lb.fit_transform(labels)

In [39]:
print(labels)

[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]


In [40]:
# perform a training and testing split, using 75% of the data for
# training and 25% for evaluation
(trainX, testX, trainY, testY) = train_test_split(np.array(data),	np.array(labels), test_size=0.25, shuffle=True)
print(trainX.shape)
print(testX.shape)

(96, 64, 64, 3)
(33, 64, 64, 3)


In [45]:
from keras.layers import Convolution2D, MaxPool2D
from keras.models import Sequential
from keras.layers.core import Flatten, Dense

model1 = Sequential()
model1.add(Convolution2D(8, (3,3), activation='relu', input_shape=(64,64,3)))
model1.add(MaxPool2D(2,2))
model1.add(Convolution2D(16, (3,3), activation='relu'))
model1.add(MaxPool2D(2,2))
#fully connected layer
model1.add(Flatten())
model1.add(Dense(100, activation='relu'))
model1.add(Dense(3, activation='softmax'))

model1.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_5 (Conv2D)            (None, 62, 62, 8)         224       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 31, 31, 8)         0         
_________________________________________________________________
conv2d_6 (Conv2D)            (None, 29, 29, 16)        1168      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 14, 14, 16)        0         
_________________________________________________________________
flatten (Flatten)            (None, 3136)              0         
_________________________________________________________________
dense (Dense)                (None, 100)               313700    
_________________________________________________________________
dense_1 (Dense)              (None, 3)                

In [46]:
from keras.models import Sequential
from keras.layers.core import Flatten
from keras.layers.core import Dense

model = Sequential(
    [
        Flatten(input_shape=(64*64*3,)),
        Dense(100, activation="relu", name="layer1"),
        Dense(16, activation="relu", name="layer2"),
        Dense(16, activation="relu", name="layer3"),
        Dense(3, activation = "softmax", name="layer4"),
    ]
)

In [47]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_1 (Flatten)          (None, 12288)             0         
_________________________________________________________________
layer1 (Dense)               (None, 100)               1228900   
_________________________________________________________________
layer2 (Dense)               (None, 16)                1616      
_________________________________________________________________
layer3 (Dense)               (None, 16)                272       
_________________________________________________________________
layer4 (Dense)               (None, 3)                 51        
Total params: 1,230,839
Trainable params: 1,230,839
Non-trainable params: 0
_________________________________________________________________


In [48]:
# train the model using the Adam optimizer
print("[INFO] training network...")
opt = Adam(lr=1e-3, decay=1e-3 / 50)
model1.compile(loss="categorical_crossentropy", optimizer=opt, metrics=["accuracy"])

[INFO] training network...


In [49]:
H = model1.fit(trainX, trainY, validation_data=(testX, testY), epochs=25, batch_size=32)

Epoch 1/25


ValueError: ignored

In [50]:
# evaluate the network
print("[INFO] evaluating network...")
predictions = model1.predict(testX, batch_size=32)
print(classification_report(testY.argmax(axis=1),
	predictions.argmax(axis=1), target_names=lb.classes_))

[INFO] evaluating network...


ValueError: ignored

In [51]:
model.save('nnmodel_scene')

Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
INFO:tensorflow:Assets written to: nnmodel_scene/assets
